# Generated by Django 5.2.1 on 2025-05-26 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationStatusUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('job_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_updates', to='track.jobapplication')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='track.applicationstatus')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
