# Generated by Django 5.2.1 on 2025-05-26 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0002_applicationstatusupdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='status',
        ),
    ]
