# Generated by Django 5.2.1 on 2025-05-26 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0003_remove_jobapplication_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='job_link',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='location',
        ),
    ]
