# Generated by Django 5.2.1 on 2025-05-27 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0005_alter_applicationstatus_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='company',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
